const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER'

const FETCHED_SPELLS = 'FETCHED_SPELLS'

const SEARCH_SPELLS = 'SEARCH_SPELLS'


export { SET_AUTHENTICATED_USER, FETCHED_SPELLS, SEARCH_SPELLS }